apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

namePrefix: kustomize-dev

replicas:
  - name: myapp
    count: 1

secretGenerator:
- name: username
  literals:
  - username=admin
- name: region
  files:
  - region=region.txt
- name: password
  envs:
  - .env